spring.application.name=MothersKitchenBackend


# ============================
# JWT CONFIG
# ============================
jwt.master_key="MothersKitchenfnbslfecbieuwlhrkjehrliwuer567890"

PGHOST=postgres.railway.internal
PGDATABASE=railway
PGUSER=postgres
PGPASSWORD=IMgikujfdPdNfucICbinNQyHxxqzjoQs
PGPORT=5432


# ============================
# Email CONFIG
# ============================

# SMTP Server
spring.mail.host=send.one.com
spring.mail.port=587
spring.mail.username=support@motherskitchen.se
spring.mail.password=Motherskitchen@007

owner.email="richanautiyal@outlook.com"

# Protocol
spring.mail.protocol=smtp

# Security
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false



# ============================
# DATABASE CONFIG (Docker)
# ============================

spring.datasource.url=jdbc:postgresql://localhost:5432/motherskitchen
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# ============================
# JPA / HIBERNATE CONFIG
# ============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Server
# ============================
server.port=8080

# ============================
# AWS
# ============================
aws.access.key=AKIAQSTSKNSXAV3NBBP5
aws.secret.key=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
aws.region=eu-north-1


#===========================
# Master LOGIN DATA
#===========================
master.admin.email=admin@motherskitchen.com
master.admin.password=$2a$12$f3iYnYGnQbn1nnFpsQxdBexe60VA.qmxv8PtVgZ9avhbr0CRMGZW6
master.admin.role=ADMIN