spring.application.name=MothersKitchenBackend

spring.mail.host=send.one.com
spring.mail.port=465
spring.mail.username=support@motherskitchen.se
spring.mail.password=YOUR_EMAIL_PASSWORD

spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
