spring.application.name=MothersKitchenBackend

# ============================
# SERVER CONFIG
# ============================
server.port=8080


# Dev mode: include errors in response
server.error.include-message=always


# ============================
# JWT CONFIG (Dev only)
# ============================
jwt.master_key=7usJ9x4KWgY2MW8v6O6BrRf9REIHj8ypT6qBkacZnJdPZp/FAP4WVa2Qa55K8YRKLi2VKxDfnAg48LPuNXRcjw==

# ============================
# Email CONFIG (Dev only)
# ============================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=9c9ae6001@smtp-brevo.com
spring.mail.password=xsmtpsib-5d82e764e9da7c45baca2e6b4290eeef820de0670c7c8cbba39a0865dc990414-rbA2SsNxMGYPsaMX
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


owner.email=richanautiyal@outlook.com

spring.mail.protocol=smtp



# ============================
# LOCAL DATABASE CONFIG
# ============================
spring.datasource.url=jdbc:postgresql://localhost:5432/motherskitchen
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP (reduces lag)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000


# ============================
# JPA / HIBERNATE
# ============================
spring.jpa.hibernate.ddl-auto=update

# IMPORTANT: Dev SQL logs only
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ============================
# AWS CONFIG (Dev only)
# ============================
aws.access.key=AKIAQSTSKNSXAV3NBBP5
aws.secret.key=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
aws.region=eu-north-1


# ============================
# MASTER ADMIN (Dev only)
# ============================
master.admin.email=admin@motherskitchen.com
master.admin.password=$2a$12$f3iYnYGnQbn1nnFpsQxdBexe60VA.qmxv8PtVgZ9avhbr0CRMGZW6
master.admin.role=ADMIN


# ============================
# NEW (Dev only)
# ============================
spring.main.lazy-initialization=false

