spring.application.name=MothersKitchenBackend


# ============================
# JWT CONFIG
# ============================
jwt.master_key="MothersKitchenfnbslfecbieuwlhrkjehrliwuer567890"



# ============================
# Email CONFIG
# ============================

spring.mail.host=send.one.com
spring.mail.port=465
spring.mail.username=support@motherskitchen.se
spring.mail.password=YOUR_EMAIL_PASSWORD

spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false


# ============================
# DATABASE CONFIG
# ============================
spring.datasource.url=jdbc:postgresql://localhost:5432/motherskitchen
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# ============================
# JPA / HIBERNATE CONFIG
# ============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================
# Server
# ============================
server.port=8080
